version: '3.9'

services:
    mongodb:
        image: mongo
        container_name: mongo_sorcery
        restart: always
        ports:
            - ${MONGODB_PORT}:${MONGODB_PORT}

    php:
        build: docker/php
        container_name: php_sorcery
        expose:
            - 9000
        restart: always
        volumes:
            - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/php/conf/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./:${PROJECT_ROOT}
        depends_on:
            - mongodb

    nginx:
        image: nginx:latest
        container_name: nginx_sorcery
        ports:
            - ${VIRTUAL_PORT}:80
        restart: always
        volumes:
            - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./:${PROJECT_ROOT}
        depends_on:
            - php
